#ifndef	xvmount_HEADER
#define	xvmount_HEADER

/*
 * xvmount_ui.h - User interface object and function declarations.
 * This file was generated by `gxv' from `xvmount.G'.
 * DO NOT EDIT BY HAND.
 */

#ifndef SVR4
EXTERN_FUNCTION( char *bindtextdomain, (const char *, const char *) );
EXTERN_FUNCTION( char *dgettext, (const char *, const char *) );
#else
#include <locale.h>
#endif

extern Attr_attribute	INSTANCE;


typedef struct {
	Xv_opaque	xmount_main;
	Xv_opaque	lists_panel;
	Xv_opaque	mount_list;
	Xv_opaque	mfs_group;
	Xv_opaque	fstab_list;
	Xv_opaque	ufs_group;
	Xv_opaque	command_mount;
	Xv_opaque	command_unmount;
	Xv_opaque	status_pane;
	Xv_opaque	command_controls;
	Xv_opaque	command_help;
	Xv_opaque	command_exit;
	Xv_opaque	command_panel;
	Xv_opaque	root_device;
	Xv_opaque	root_mnt;
	Xv_opaque	root_left_group;
	Xv_opaque	root_fsystem;
	Xv_opaque	root_options;
	Xv_opaque	root_right_group;
	Xv_opaque	root_command_unmount;
	Xv_opaque	root_command_mount;
	Xv_opaque	root_command_group;
} xvmount_xmount_main_objects;

extern xvmount_xmount_main_objects	*xvmount_xmount_main_objects_initialize(xvmount_xmount_main_objects *, Xv_opaque);

extern Xv_opaque	xvmount_xmount_main_xmount_main_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_lists_panel_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_mount_list_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_mfs_group_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_fstab_list_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_ufs_group_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_command_mount_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_command_unmount_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_status_pane_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_command_controls_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_command_help_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_command_exit_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_command_panel_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_device_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_mnt_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_left_group_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_fsystem_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_options_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_right_group_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_command_unmount_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_command_mount_create(xvmount_xmount_main_objects *, Xv_opaque);
extern Xv_opaque	xvmount_xmount_main_root_command_group_create(xvmount_xmount_main_objects *, Xv_opaque);

typedef struct {
	Xv_opaque	about_box;
	Xv_opaque	about_panel;
	Xv_opaque	about_text;
	Xv_opaque	about_text_1;
	Xv_opaque	about_text_2;
	Xv_opaque	about_text_3;
	Xv_opaque	text_group;
	Xv_opaque	about_close;
	Xv_opaque	ok_group;
} xvmount_about_box_objects;

extern xvmount_about_box_objects	*xvmount_about_box_objects_initialize(xvmount_about_box_objects *, Xv_opaque);

extern Xv_opaque	xvmount_about_box_about_box_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_about_panel_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_about_text_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_about_text_1_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_about_text_2_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_about_text_3_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_text_group_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_about_close_create(xvmount_about_box_objects *, Xv_opaque);
extern Xv_opaque	xvmount_about_box_ok_group_create(xvmount_about_box_objects *, Xv_opaque);
#endif
