/*
 * xvmount_ui.c - User interface object initialization functions.
 * This file was generated by `gxv' from `xvmount.G'.
 * DO NOT EDIT BY HAND.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/canvas.h>
#include <xview/panel.h>
#include <xview/scrollbar.h>
#include <xview/svrimage.h>
#include <xview/termsw.h>
#include <xview/text.h>
#include <xview/tty.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "xvmount_ui.h"

/*
 * Initialize an instance of object `xmount_main'.
 */
xvmount_xmount_main_objects *
xvmount_xmount_main_objects_initialize(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (xvmount_xmount_main_objects *) calloc(1, sizeof (xvmount_xmount_main_objects))))
		return (xvmount_xmount_main_objects *) NULL;
	if (!ip->xmount_main)
		ip->xmount_main = xvmount_xmount_main_xmount_main_create(ip, owner);
	if (!ip->lists_panel)
		ip->lists_panel = xvmount_xmount_main_lists_panel_create(ip, ip->xmount_main);
	if (!ip->mount_list)
		ip->mount_list = xvmount_xmount_main_mount_list_create(ip, ip->lists_panel);
	if (!ip->mfs_group)
		ip->mfs_group = xvmount_xmount_main_mfs_group_create(ip, ip->lists_panel);
	if (!ip->fstab_list)
		ip->fstab_list = xvmount_xmount_main_fstab_list_create(ip, ip->lists_panel);
	if (!ip->ufs_group)
		ip->ufs_group = xvmount_xmount_main_ufs_group_create(ip, ip->lists_panel);
	if (!ip->command_mount)
		ip->command_mount = xvmount_xmount_main_command_mount_create(ip, ip->lists_panel);
	if (!ip->command_unmount)
		ip->command_unmount = xvmount_xmount_main_command_unmount_create(ip, ip->lists_panel);
	window_fit(ip->lists_panel);
	
	if (!ip->status_pane)
		ip->status_pane = xvmount_xmount_main_status_pane_create(ip, ip->xmount_main);
	if (!ip->command_controls)
		ip->command_controls = xvmount_xmount_main_command_controls_create(ip, ip->xmount_main);
	if (!ip->command_help)
		ip->command_help = xvmount_xmount_main_command_help_create(ip, ip->command_controls);
	if (!ip->command_exit)
		ip->command_exit = xvmount_xmount_main_command_exit_create(ip, ip->command_controls);
	if (!ip->command_panel)
		ip->command_panel = xvmount_xmount_main_command_panel_create(ip, ip->xmount_main);
	if (!ip->root_device)
		ip->root_device = xvmount_xmount_main_root_device_create(ip, ip->command_panel);
	if (!ip->root_mnt)
		ip->root_mnt = xvmount_xmount_main_root_mnt_create(ip, ip->command_panel);
	if (!ip->root_left_group)
		ip->root_left_group = xvmount_xmount_main_root_left_group_create(ip, ip->command_panel);
	if (!ip->root_fsystem)
		ip->root_fsystem = xvmount_xmount_main_root_fsystem_create(ip, ip->command_panel);
	if (!ip->root_options)
		ip->root_options = xvmount_xmount_main_root_options_create(ip, ip->command_panel);
	if (!ip->root_right_group)
		ip->root_right_group = xvmount_xmount_main_root_right_group_create(ip, ip->command_panel);
	if (!ip->root_command_unmount)
		ip->root_command_unmount = xvmount_xmount_main_root_command_unmount_create(ip, ip->command_panel);
	if (!ip->root_command_mount)
		ip->root_command_mount = xvmount_xmount_main_root_command_mount_create(ip, ip->command_panel);
	if (!ip->root_command_group)
		ip->root_command_group = xvmount_xmount_main_root_command_group_create(ip, ip->command_panel);
	window_fit(ip->command_panel);
	
	window_fit(ip->xmount_main);
	
	xv_set(ip->lists_panel, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->status_pane, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->command_controls, XV_WIDTH, WIN_EXTEND_TO_EDGE, NULL);
	xv_set(ip->command_panel,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `xmount_main' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_xmount_main_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern Notify_value	xvmount_xmount_main_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	Xv_opaque		xmount_main_image;
	static unsigned short	xmount_main_bits[] = {
#include "glyphs/mount_icon.glyph"
	};
	
	xmount_main_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, xmount_main_bits,
		XV_WIDTH, 64,
		XV_HEIGHT, 64,
		NULL);
	obj = xv_create(owner, FRAME,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "xmount_main",
		XV_USE_DB,
			XV_WIDTH, 527,
			XV_HEIGHT, 387,
			NULL,
		XV_LABEL, dgettext("xvmount_labels", "XMount"),
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_ICON, xv_create(XV_NULL, ICON,
			ICON_IMAGE, xmount_main_image,
			XV_LABEL, dgettext("xvmount_labels", "XMount"),
			NULL),
		NULL);
	xv_set(obj, WIN_CONSUME_EVENTS,
		LOC_WINEXIT,
		NULL, NULL);
	notify_interpose_event_func(obj,
		(Notify_func) xvmount_xmount_main_event_callback, NOTIFY_SAFE);
	return obj;
}

/*
 * Create object `lists_panel' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_lists_panel_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "lists_panel",
		XV_USE_DB,
			XV_X, 0,
			XV_Y, 0,
			XV_WIDTH, WIN_EXTEND_TO_EDGE,
			XV_HEIGHT, 189,
			NULL,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `mount_list' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_mount_list_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "mount_list",
		XV_HELP_DATA, "xvmount:mount_list",
		XV_USE_DB,
			XV_X, 10,
			XV_Y, 10,
			PANEL_LIST_WIDTH, 200,
			PANEL_LIST_DISPLAY_ROWS, 7,
			NULL,
		PANEL_LIST_TITLE, dgettext("xvmount_labels", "mounted:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `mfs_group' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_mfs_group_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "mfs_group",
		XV_X, 10,
		XV_Y, 10,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->mount_list,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `fstab_list' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_fstab_list_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_LIST,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "fstab_list",
		XV_USE_DB,
			XV_X, 300,
			XV_Y, 10,
			PANEL_LIST_WIDTH, 200,
			PANEL_LIST_DISPLAY_ROWS, 7,
			NULL,
		PANEL_LIST_TITLE, dgettext("xvmount_labels", "available:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, TRUE,
		PANEL_CHOOSE_ONE, TRUE,
		PANEL_CHOOSE_NONE, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `ufs_group' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_ufs_group_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "ufs_group",
		XV_X, 300,
		XV_Y, 10,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->fstab_list,
			NULL,
		NULL);
	return obj;
}

/*
 * Create object `command_mount' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_command_mount_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern void		cmd_unmount(Panel_item, Event *);
	Xv_opaque	obj;
	Xv_opaque		command_mount_image;
	static unsigned short	command_mount_bits[] = {
#include "glyphs/unmount.glyph"
	};
	
	command_mount_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, command_mount_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "command_mount",
		XV_HELP_DATA, "xvmount:command_mount",
		XV_USE_DB,
			XV_X, 240,
			XV_Y, 30,
			NULL,
		PANEL_LABEL_IMAGE, command_mount_image,
		PANEL_NOTIFY_PROC, cmd_unmount,
		NULL);
	return obj;
}

/*
 * Create object `command_unmount' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_command_unmount_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern void		cmd_mount(Panel_item, Event *);
	Xv_opaque	obj;
	Xv_opaque		command_unmount_image;
	static unsigned short	command_unmount_bits[] = {
#include "glyphs/mount.glyph"
	};
	
	command_unmount_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, command_unmount_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "command_unmount",
		XV_HELP_DATA, "xvmount:command_unmount",
		XV_USE_DB,
			XV_X, 240,
			XV_Y, 90,
			NULL,
		PANEL_LABEL_IMAGE, command_unmount_image,
		PANEL_NOTIFY_PROC, cmd_mount,
		NULL);
	return obj;
}

/*
 * Create object `status_pane' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_status_pane_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern Notify_value	xvmount_xmount_main_status_pane_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	
	obj = xv_create(owner, TEXTSW,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "status_pane",
		XV_USE_DB,
			XV_X, 0,
			XV_Y, (int)xv_get(ip->lists_panel, XV_Y) +
			      (int)xv_get(ip->lists_panel, XV_HEIGHT) + 2,
			XV_WIDTH, WIN_EXTEND_TO_EDGE,
			XV_HEIGHT, 61,
			NULL,
		OPENWIN_SHOW_BORDERS, TRUE,
		TEXTSW_BROWSING, TRUE,
		TEXTSW_DISABLE_LOAD, TRUE,
		NULL);
	xv_set(textsw_first(obj), WIN_CONSUME_EVENTS,
		WIN_MOUSE_BUTTONS,
		NULL, NULL);
	notify_interpose_event_func(textsw_first(obj),
		(Notify_func) xvmount_xmount_main_status_pane_event_callback, NOTIFY_SAFE);
	return obj;
}

/*
 * Create object `command_controls' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_command_controls_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "command_controls",
		XV_USE_DB,
			XV_X, 0,
			XV_Y, (int)xv_get(ip->status_pane, XV_Y) +
			      (int)xv_get(ip->status_pane, XV_HEIGHT),
			XV_WIDTH, WIN_EXTEND_TO_EDGE,
			XV_HEIGHT, 60,
			NULL,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `command_help' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_command_help_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern void		cmd_help(Panel_item, Event *);
	Xv_opaque	obj;
	Xv_opaque		command_help_image;
	static unsigned short	command_help_bits[] = {
#include "glyphs/smile.glyph"
	};
	
	command_help_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, command_help_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "command_help",
		XV_USE_DB,
			XV_X, 10,
			XV_Y, 10,
			NULL,
		PANEL_LABEL_IMAGE, command_help_image,
		PANEL_NOTIFY_PROC, cmd_help,
		NULL);
	return obj;
}

/*
 * Create object `command_exit' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_command_exit_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern void		cmd_exit(Panel_item, Event *);
	Xv_opaque	obj;
	Xv_opaque		command_exit_image;
	static unsigned short	command_exit_bits[] = {
#include "glyphs/unsmile.glyph"
	};
	
	command_exit_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, command_exit_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "command_exit",
		XV_USE_DB,
			XV_X, 60,
			XV_Y, 10,
			NULL,
		PANEL_LABEL_IMAGE, command_exit_image,
		PANEL_NOTIFY_PROC, cmd_exit,
		NULL);
	return obj;
}

/*
 * Create object `command_panel' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_command_panel_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "command_panel",
		XV_HELP_DATA, "xvmount:command_panel",
		XV_USE_DB,
			XV_X, 0,
			XV_Y, (int)xv_get(ip->command_controls, XV_Y) +
			      (int)xv_get(ip->command_controls, XV_HEIGHT),
			XV_WIDTH, WIN_EXTEND_TO_EDGE,
			XV_HEIGHT, WIN_EXTEND_TO_EDGE,
			NULL,
		WIN_BORDER, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `root_device' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_device_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_device",
		XV_HELP_DATA, "xvmount:root_device",
		XV_USE_DB,
			XV_X, 10,
			XV_Y, 10,
			PANEL_VALUE_DISPLAY_LENGTH, 10,
			PANEL_VALUE_STORED_LENGTH, 80,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "device:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `root_mnt' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_mnt_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_mnt",
		XV_HELP_DATA, "xvmount:root_mnt",
		XV_USE_DB,
			XV_X, 27,
			XV_Y, 35,
			PANEL_VALUE_DISPLAY_LENGTH, 8,
			PANEL_VALUE_STORED_LENGTH, 80,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "mnt:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `root_left_group' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_left_group_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_left_group",
		XV_X, 10,
		XV_Y, 10,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->root_device,
			ip->root_mnt,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `root_fsystem' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_fsystem_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_CHOICE, PANEL_DISPLAY_LEVEL, PANEL_CURRENT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_fsystem",
		XV_HELP_DATA, "xvmount:root_fsystem",
		XV_USE_DB,
			XV_X, 175,
			XV_Y, 10,
			PANEL_CHOICE_NCOLS, 1,
			NULL,
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "file systems:"),
		PANEL_CHOICE_STRINGS,
			dgettext("xvmount_labels", "hpfs"),
			dgettext("xvmount_labels", "msdos"),
			dgettext("xvmount_labels", "sysv"),
			dgettext("xvmount_labels", "vfat"),
			dgettext("xvmount_labels", "ext2"),
			dgettext("xvmount_labels", "fat"),
			dgettext("xvmount_labels", "isofs"),
			dgettext("xvmount_labels", "minix"),
			dgettext("xvmount_labels", "ncpfs"),
			dgettext("xvmount_labels", "smbfs"),
			dgettext("xvmount_labels", "ufs"),
			dgettext("xvmount_labels", "umsdos"),
			dgettext("xvmount_labels", "proc"),
			dgettext("xvmount_labels", "xiafs"),
			dgettext("xvmount_labels", "iso9660"),
			dgettext("xvmount_labels", "swap"),
			dgettext("xvmount_labels", "nfs"),
			dgettext("xvmount_labels", "[unspecified]"),
			NULL,
		PANEL_DEFAULT_VALUE, 1,
		PANEL_VALUE, 17,
		NULL);
	return obj;
}

/*
 * Create object `root_options' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_options_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_TEXT,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_options",
		XV_HELP_DATA, "xvmount:root_options",
		XV_USE_DB,
			XV_X, 183,
			XV_Y, 43,
			PANEL_VALUE_DISPLAY_LENGTH, 8,
			PANEL_VALUE_STORED_LENGTH, 80,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "additionnal:"),
		PANEL_LAYOUT, PANEL_HORIZONTAL,
		PANEL_READ_ONLY, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `root_right_group' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_right_group_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_right_group",
		XV_X, 175,
		XV_Y, 10,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->root_fsystem,
			ip->root_options,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_LABELS,
		GROUP_VERTICAL_SPACING, 10,
		GROUP_ANCHOR_OBJ, ip->root_left_group,
		GROUP_ANCHOR_POINT, GROUP_NORTHEAST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 30,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

/*
 * Create object `root_command_unmount' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_command_unmount_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern void		root_cmd_unmount(Panel_item, Event *);
	Xv_opaque	obj;
	Xv_opaque		root_command_unmount_image;
	static unsigned short	root_command_unmount_bits[] = {
#include "glyphs/unmount.glyph"
	};
	
	root_command_unmount_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, root_command_unmount_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_command_unmount",
		XV_HELP_DATA, "xvmount:root_command_unmount",
		XV_USE_DB,
			XV_X, 397,
			XV_Y, 10,
			NULL,
		PANEL_LABEL_IMAGE, root_command_unmount_image,
		PANEL_NOTIFY_PROC, root_cmd_unmount,
		NULL);
	return obj;
}

/*
 * Create object `root_command_mount' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_command_mount_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	extern void		root_cmd_mount(Panel_item, Event *);
	Xv_opaque	obj;
	Xv_opaque		root_command_mount_image;
	static unsigned short	root_command_mount_bits[] = {
#include "glyphs/mount.glyph"
	};
	
	root_command_mount_image = xv_create(XV_NULL, SERVER_IMAGE,
		SERVER_IMAGE_DEPTH, 1,
		SERVER_IMAGE_BITS, root_command_mount_bits,
		XV_WIDTH, 32,
		XV_HEIGHT, 32,
		NULL);
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_command_mount",
		XV_HELP_DATA, "xvmount:root_command_mount",
		XV_USE_DB,
			XV_X, 447,
			XV_Y, 10,
			NULL,
		PANEL_LABEL_IMAGE, root_command_mount_image,
		PANEL_NOTIFY_PROC, root_cmd_mount,
		NULL);
	return obj;
}

/*
 * Create object `root_command_group' in the specified instance.
 */
Xv_opaque
xvmount_xmount_main_root_command_group_create(xvmount_xmount_main_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "root_command_group",
		XV_X, 397,
		XV_Y, 10,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->root_command_unmount,
			ip->root_command_mount,
			NULL,
		GROUP_ANCHOR_OBJ, ip->root_right_group,
		GROUP_ANCHOR_POINT, GROUP_NORTHEAST,
		GROUP_REFERENCE_POINT, GROUP_NORTHWEST,
		GROUP_HORIZONTAL_OFFSET, 10,
		GROUP_VERTICAL_OFFSET, 0,
		NULL);
	return obj;
}

/*
 * Initialize an instance of object `about_box'.
 */
xvmount_about_box_objects *
xvmount_about_box_objects_initialize(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	if (!ip && !(ip = (xvmount_about_box_objects *) calloc(1, sizeof (xvmount_about_box_objects))))
		return (xvmount_about_box_objects *) NULL;
	if (!ip->about_box)
		ip->about_box = xvmount_about_box_about_box_create(ip, owner);
	if (!ip->about_panel)
		ip->about_panel = xvmount_about_box_about_panel_create(ip, ip->about_box);
	if (!ip->about_text)
		ip->about_text = xvmount_about_box_about_text_create(ip, ip->about_panel);
	if (!ip->about_text_1)
		ip->about_text_1 = xvmount_about_box_about_text_1_create(ip, ip->about_panel);
	if (!ip->about_text_2)
		ip->about_text_2 = xvmount_about_box_about_text_2_create(ip, ip->about_panel);
	if (!ip->about_text_3)
		ip->about_text_3 = xvmount_about_box_about_text_3_create(ip, ip->about_panel);
	if (!ip->text_group)
		ip->text_group = xvmount_about_box_text_group_create(ip, ip->about_panel);
	if (!ip->about_close)
		ip->about_close = xvmount_about_box_about_close_create(ip, ip->about_panel);
	if (!ip->ok_group)
		ip->ok_group = xvmount_about_box_ok_group_create(ip, ip->about_panel);
	window_fit(ip->about_panel);
	
	window_fit(ip->about_box);
	
	xv_set(ip->about_panel,
		XV_WIDTH, WIN_EXTEND_TO_EDGE,
		XV_HEIGHT, WIN_EXTEND_TO_EDGE,
		NULL);
	return ip;
}

/*
 * Create object `about_box' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_box_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	extern Notify_value	xvmount_about_box_event_callback(Xv_window, Event *, Notify_arg, Notify_event_type);
	Xv_opaque	obj;
	
	obj = xv_create(owner, FRAME_CMD,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_box",
		XV_USE_DB,
			XV_WIDTH, 190,
			XV_HEIGHT, 138,
			NULL,
		XV_LABEL, dgettext("xvmount_labels", "About XMount"),
		XV_SHOW, FALSE,
		FRAME_SHOW_FOOTER, FALSE,
		FRAME_SHOW_RESIZE_CORNER, FALSE,
		FRAME_CMD_PUSHPIN_IN, FALSE,
		NULL);
	xv_set(obj, WIN_CONSUME_EVENTS,
		NULL, NULL);
	notify_interpose_event_func(obj,
		(Notify_func) xvmount_about_box_event_callback, NOTIFY_SAFE);
	xv_set(xv_get(obj, FRAME_CMD_PANEL), WIN_SHOW, FALSE, NULL);
	return obj;
}

/*
 * Create object `about_panel' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_panel_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_panel",
		XV_USE_DB,
			XV_X, 0,
			XV_Y, 0,
			XV_WIDTH, WIN_EXTEND_TO_EDGE,
			XV_HEIGHT, WIN_EXTEND_TO_EDGE,
			NULL,
		WIN_BORDER, FALSE,
		NULL);
	return obj;
}

/*
 * Create object `about_text' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_text_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_text",
		XV_USE_DB,
			XV_X, 52,
			XV_Y, 10,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "XMount 1.0"),
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `about_text_1' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_text_1_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_text_1",
		XV_USE_DB,
			XV_X, 10,
			XV_Y, 33,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "(c) Daniel Doubrovkine"),
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `about_text_2' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_text_2_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_text_2",
		XV_USE_DB,
			XV_X, 69,
			XV_Y, 56,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "UniGe"),
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `about_text_3' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_text_3_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_MESSAGE,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_text_3",
		XV_USE_DB,
			XV_X, 73,
			XV_Y, 79,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "1997"),
		PANEL_LABEL_BOLD, TRUE,
		NULL);
	return obj;
}

/*
 * Create object `text_group' in the specified instance.
 */
Xv_opaque
xvmount_about_box_text_group_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "text_group",
		XV_X, 10,
		XV_Y, 10,
		GROUP_TYPE, GROUP_COLUMN,
		GROUP_MEMBERS,
			ip->about_text,
			ip->about_text_1,
			ip->about_text_2,
			ip->about_text_3,
			NULL,
		GROUP_COLUMN_ALIGNMENT, GROUP_VERTICAL_CENTERS,
		GROUP_VERTICAL_SPACING, 10,
		NULL);
	return obj;
}

/*
 * Create object `about_close' in the specified instance.
 */
Xv_opaque
xvmount_about_box_about_close_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	extern void		about_box_close(Panel_item, Event *);
	Xv_opaque	obj;
	
	obj = xv_create(owner, PANEL_BUTTON,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "about_close",
		XV_USE_DB,
			XV_X, 57,
			XV_Y, 102,
			NULL,
		PANEL_LABEL_STRING, dgettext("xvmount_labels", "Thanks!"),
		PANEL_NOTIFY_PROC, about_box_close,
		NULL);
	return obj;
}

/*
 * Create object `ok_group' in the specified instance.
 */
Xv_opaque
xvmount_about_box_ok_group_create(xvmount_about_box_objects *ip, Xv_opaque owner)
{
	Xv_opaque	obj;
	
	obj = xv_create(owner, GROUP,
		XV_KEY_DATA, INSTANCE, ip,
		XV_INSTANCE_NAME, "ok_group",
		XV_X, 57,
		XV_Y, 102,
		GROUP_TYPE, GROUP_NONE,
		GROUP_MEMBERS,
			ip->about_close,
			NULL,
		GROUP_ANCHOR_OBJ, ip->text_group,
		GROUP_ANCHOR_POINT, GROUP_SOUTH,
		GROUP_REFERENCE_POINT, GROUP_NORTH,
		GROUP_HORIZONTAL_OFFSET, 0,
		GROUP_VERTICAL_OFFSET, 10,
		NULL);
	return obj;
}

