/*
 * xvmount_stubs.c - Notify and event callback function stubs.
 * This file was generated by `gxv' from `xvmount.G'.
 */

#include <stdio.h>
#include <sys/param.h>
#include <sys/types.h>
#include <xview/xview.h>
#include <xview/panel.h>
#include <xview/textsw.h>
#include <xview/xv_xrect.h>
#include <group.h>
#include "xvmount_ui.h"

void		xmount_main_resize(Xv_window, Event *, Notify_arg, Notify_event_type);
void		xmount_onterminate(Xv_window, Event *, Notify_arg, Notify_event_type);
void		about_box_resize(Xv_window, Event *, Notify_arg, Notify_event_type);
void		interpose_menu_popup(Xv_window, Event *, Notify_arg, Notify_event_type);

/*
 * Global object definitions.
 */
xvmount_xmount_main_objects	*xvmount_xmount_main;

/*
 * Global object definitions.
 */
xvmount_xmount_main_objects	*Xvmount_xmount_main;
xvmount_about_box_objects	*Xvmount_about_box;

#include "vcore.c"

#ifdef MAIN

/*
 * Instance XV_KEY_DATA key.  An instance is a set of related
 * user interface objects.  A pointer to an object's instance
 * is stored under this key in every object.  This must be a
 * global variable.
 */
Attr_attribute	INSTANCE;

main(int argc, char **argv){
	xv_init(XV_INIT_ARGC_PTR_ARGV, &argc, argv, XV_USE_LOCALE, TRUE, NULL);
	init_core();
	exit(0);
	}
#endif


/*
 * Event callback function for `xmount_main'.
 */
Notify_value
xvmount_xmount_main_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);

	if (threads_running!=2) {
		decmutex(&threads_running, &threads_running_mutex, &threads_running_condition);
      		pthread_exit(0);
		}

	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == WIN_RESIZE)
	{
		xmount_main_resize(win, event, arg, type);
	}
	
	if (event_action(event) == LOC_WINEXIT)
	{
		xmount_onterminate(win, event, arg, type);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * User-defined action for `xmount_main'.
 */
void
xmount_main_resize(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	int hmin = 300;
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);

	resize_lists(ip);
	if (xv_get(ip->xmount_main, XV_WIDTH, INSTANCE) < 500) xv_set(ip->xmount_main, XV_WIDTH, 500, NULL);
	if (!getuid()) hmin+=70;
	if (xv_get(ip->xmount_main, XV_HEIGHT, INSTANCE) < hmin) xv_set(ip->xmount_main, XV_HEIGHT, hmin, NULL); 	
	resize_lists(ip);
}

/*
 * Notify callback function for `command_unmount'.
 */
void
cmd_unmount(Panel_item item, Event *event)
{
	int l_items;
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);

	l_items = xv_get(ip->mount_list, PANEL_LIST_NROWS, INSTANCE);
	if (l_items)
	while (l_items--)
	   if (xv_get(ip->mount_list, PANEL_LIST_SELECTED, l_items, INSTANCE))
		mount_unmount_xview(
			strdup((char *) xv_get(ip->mount_list, PANEL_LIST_STRING, l_items, INSTANCE)), 0);
		
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `command_mount'.
 */
void
cmd_mount(Panel_item item, Event *event)
{
	int l_items;
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	l_items = xv_get(ip->fstab_list, PANEL_LIST_NROWS, INSTANCE);	
	if (l_items)
	while (l_items--)
	   if (xv_get(ip->fstab_list, PANEL_LIST_SELECTED, l_items, INSTANCE))
		mount_unmount_xview(strdup((char *) xv_get(ip->fstab_list, PANEL_LIST_STRING, l_items, INSTANCE)), 1);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `root_command_mount'.
 */
void
root_cmd_mount(Panel_item item, Event *event)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
 	root_mount_unmount(
		(char *) xv_get(ip->root_device, PANEL_VALUE, NULL),
		(char *) xv_get(ip->root_mnt, PANEL_VALUE, NULL),
		(char *) (char *) xv_get(ip->root_fsystem, PANEL_CHOICE_STRING, 
				  xv_get(ip->root_fsystem, PANEL_VALUE, NULL), NULL),
	 	(char *) xv_get(ip->root_options, PANEL_VALUE, NULL),
		1);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `root_command_unmount'.
 */
void
root_cmd_unmount(Panel_item item, Event *event)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);

	root_mount_unmount(
		(char *) xv_get(ip->root_device, PANEL_VALUE, NULL),
		(char *) xv_get(ip->root_mnt, PANEL_VALUE, NULL),
		(char *) (char *) xv_get(ip->root_fsystem, PANEL_CHOICE_STRING, xv_get(ip->root_fsystem, PANEL_VALUE, NULL), NULL),
	 	(char *) xv_get(ip->root_options, PANEL_VALUE, NULL), 0);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `command_help'.
 */
void
cmd_help(Panel_item item, Event *event)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	xv_set(Xvmount_about_box->about_box, FRAME_CMD_PUSHPIN_IN, TRUE, NULL);
	xv_set(Xvmount_about_box->about_box, XV_SHOW, TRUE, NULL);

	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Notify callback function for `command_exit'.
 */
void
cmd_exit(Panel_item item, Event *event)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	/*
	textsw_reset(ip->status_pane, 0, 0);
	xmount_terminated = 1;
	*/
	xv_destroy_safe(ip->xmount_main);

	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * User-defined action for `xmount_main'.
 */
void
xmount_onterminate(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	}

/*
 * Notify callback function for `about_close'.
 */
void
about_box_close(Panel_item item, Event *event)
{
	xvmount_about_box_objects *ip = (xvmount_about_box_objects *) xv_get(item, XV_KEY_DATA, INSTANCE);
	
	xv_set(Xvmount_about_box->about_box, FRAME_CMD_PUSHPIN_IN, FALSE, NULL);
	xv_set(Xvmount_about_box->about_box, XV_SHOW, FALSE, NULL);
	
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	/* gxv_end_connections */

}

/*
 * Event callback function for `about_box'.
 */
Notify_value
xvmount_about_box_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	xvmount_about_box_objects *ip = (xvmount_about_box_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
		
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == WIN_RESIZE)
	{
		about_box_resize(win, event, arg, type);
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * User-defined action for `about_box'.
 */
void
about_box_resize(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	xvmount_about_box_objects *ip = (xvmount_about_box_objects *) xv_get(win, XV_KEY_DATA, INSTANCE);
	/*
	int form_width = xv_get(ip->about_box, XV_WIDTH, INSTANCE);
	xv_set(ip->about_text, XV_X, (int) ((form_width - xv_get(ip->about_text, XV_WIDTH, INSTANCE))/2), NULL);
	xv_set(ip->about_text_1, XV_X, (int) ((form_width - xv_get(ip->about_text_1, XV_WIDTH, INSTANCE))/2), NULL);
	xv_set(ip->about_text_2, XV_X, (int) ((form_width - xv_get(ip->about_text_2, XV_WIDTH, INSTANCE))/2), NULL);
	xv_set(ip->about_text_3, XV_X, (int) ((form_width - xv_get(ip->about_text_3, XV_WIDTH, INSTANCE))/2), NULL);
	window_fit(ip->about_panel);	*/

	window_fit(ip->about_box);	
}

/*
 * Event callback function for `status_pane'.
 */
Notify_value
xvmount_xmount_main_status_pane_event_callback(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(xv_get(win, XV_OWNER), XV_KEY_DATA, INSTANCE);
		
	/* gxv_start_connections DO NOT EDIT THIS SECTION */

	if (event_action(event) == ACTION_MENU)
	{
		return NOTIFY_DONE;
		/*interpose_menu_popup(win, event, arg, type);*/
	}
	
	/* gxv_end_connections */

	return notify_next_event_func(win, (Notify_event) event, arg, type);
}

/*
 * User-defined action for `status_pane'.
 */
void
interpose_menu_popup(Xv_window win, Event *event, Notify_arg arg, Notify_event_type type)
{
	xvmount_xmount_main_objects *ip = (xvmount_xmount_main_objects *) xv_get(xv_get(win, XV_OWNER), XV_KEY_DATA, INSTANCE);
	
	/*fprintf(stderr, "xvmount: interpose_menu_popup: event %d\n", event_id(event));*/
}
